core = 7.x
api = 2
; -------------------------------------------------------------------------------
; Drupal Version
; -------------------------------------------------------------------------------

projects[drupal][version] = "7.31"

; -------------------------------------------------------------------------------
; Removed contrib modules
; -------------------------------------------------------------------------------

; projects[context_inline_editor][version] = "1.0-beta1"
; projects[backup_migrate_files][version] = "1.x-dev"

; -------------------------------------------------------------------------------
; Contributed modules
; -------------------------------------------------------------------------------

projects[block_titlelink][version] = "1.3"
projects[block_titlelink][subdir] = "contrib"
projects[cbc][version] = "1.0"
projects[cbc][subdir] = "contrib"
projects[context_accordion][version] = "1.0"
projects[context_accordion][subdir] = "contrib"
projects[context_http_headers][version] = "1.0"
projects[context_http_headers][subdir] = "contrib"
projects[context_list][version] = "1.1"
projects[context_list][subdir] = "contrib"
projects[context_list_active][version] = "1.0-alpha2"
projects[context_list_active][subdir] = "contrib"
projects[date][version] = "2.9-alpha1"
projects[date][subdir] = "contrib"
projects[date_ical][version] = "2.13"
projects[date_ical][subdir] = "contrib"
projects[entityreference][version] = "1.1"
projects[entityreference][subdir] = "contrib"
projects[field_group][version] = "1.4"
projects[field_group][subdir] = "contrib"
projects[insert][version] = "1.3"
projects[insert][subdir] = "contrib"
projects[menu_position][version] = "1.1"
projects[menu_position][subdir] = "contrib"
projects[rules][version] = "2.7"
projects[rules][subdir] = "contrib"
projects[transliteration][version] = "3.2"
projects[transliteration][subdir] = "contrib"
projects[workbench][version] = "1.2"
projects[workbench][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"
projects[admin_menu][subdir] = "contrib"
projects[bean][version] = "1.7"
projects[bean][subdir] = "contrib"
projects[bundle_copy][version] = "1.1"
projects[bundle_copy][subdir] = "contrib"
projects[delta][version] = "3.0-beta11"
projects[delta][subdir] = "contrib"
projects[features][version] = "2.2"
projects[features][subdir] = "contrib"
projects[filefield_paths][version] = "1.0-beta4"
projects[filefield_paths][subdir] = "contrib"
projects[job_scheduler][version] = "2.0-alpha3"
projects[job_scheduler][subdir] = "contrib"
projects[metatag][version] = "1.0-rc2"
projects[metatag][subdir] = "contrib"
projects[pathauto][version] = "1.2"
projects[pathauto][subdir] = "contrib"
projects[services][version] = "3.7"
projects[services][subdir] = "contrib"
projects[views][version] = "3.8"
projects[views][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.2"
projects[views_bulk_operations][subdir] = "contrib"
projects[admin_views][version] = "1.3"
projects[admin_views][subdir] = "contrib"
projects[views_slideshow][version] = "3.1"
projects[views_slideshow][subdir] = "contrib"
projects[views_data_export][version] = "3.0-beta8"
projects[views_data_export][subdir] = "contrib"
projects[views_field_view][version] = "1.1"
projects[views_field_view][subdir] = "contrib"
projects[workbench_access][version] = "1.2"
projects[workbench_access][subdir] = "contrib"
projects[better_exposed_filters][version] = "3.0-beta4"
projects[better_exposed_filters][subdir] = "contrib"
projects[calendar][version] = "3.4"
projects[calendar][subdir] = "contrib"
projects[diff][version] = "3.2"
projects[diff][subdir] = "contrib"
projects[feeds][version] = "2.0-alpha8"
projects[feeds][subdir] = "contrib"
projects[geofield][version] = "1.2"
projects[geofield][subdir] = "contrib"
projects[jw_player][version] = "1.0-alpha1"
projects[jw_player][subdir] = "contrib"
projects[module_filter][version] = "1.8"
projects[module_filter][subdir] = "contrib"
; Do not download openlayers. 2.0-beta9 includes a .make file that references a library that
; fails to download. Downloading the -dev version gets around that issue, but leaves us
; with a one-off of openlayers in sites/default/modules/contrib. We don't want that.
; projects[openlayers][version] = "2.0-beta9"
; projects[openlayers][subdir] = "contrib"
projects[pathologic][version] = "2.12"
projects[pathologic][subdir] = "contrib"
projects[site_verify][version] = "1.1"
projects[site_verify][subdir] = "contrib"
projects[workbench_moderation][version] = "1.3"
projects[workbench_moderation][subdir] = "contrib"
projects[advanced_help][version] = "1.1"
projects[advanced_help][subdir] = "contrib"
projects[better_formats][version] = "1.0-beta1"
projects[better_formats][subdir] = "contrib"
projects[computed_field][version] = "1.0"
projects[computed_field][subdir] = "contrib"
projects[js_injector][version] = "2.1"
projects[js_injector][subdir] = "contrib"
projects[ds][version] = "2.6"
projects[ds][subdir] = "contrib"
projects[feeds_tamper][version] = "1.0"
projects[feeds_tamper][subdir] = "contrib"
projects[geophp][version] = "1.7"
projects[geophp][subdir] = "contrib"
projects[libraries][version] = "2.2"
projects[libraries][subdir] = "contrib"
projects[mollom][version] = "2.10"
projects[mollom][subdir] = "contrib"
projects[proj4js][version] = "1.2"
projects[proj4js][subdir] = "contrib"
projects[strongarm][version] = "2.0"
projects[strongarm][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"
projects[wysiwyg][subdir] = "contrib"
projects[auto_nodetitle][version] = "1.0"
projects[auto_nodetitle][subdir] = "contrib"
projects[biblio][version] = "1.0-rc7"
projects[biblio][subdir] = "contrib"
projects[content_access][version] = "1.2-beta2"
projects[content_access][subdir] = "contrib"
projects[ctools][version] = "1.4"
projects[ctools][subdir] = "contrib"
projects[email][version] = "1.3"
projects[email][subdir] = "contrib"
projects[feeds_xpathparser][version] = "1.0-beta4"
projects[feeds_xpathparser][subdir] = "contrib"
projects[globalredirect][version] = "1.5"
projects[globalredirect][subdir] = "contrib"
projects[link][version] = "1.2"
projects[link][subdir] = "contrib"
projects[node_clone][version] = "1.0-rc2"
projects[node_clone][subdir] = "contrib"
projects[redirect][version] = "1.0-beta4"
projects[redirect][subdir] = "contrib"
projects[path_redirect_import][version] = "1.0-rc4"
projects[path_redirect_import][subdir] = "contrib"
projects[taxonomy_manager][version] = "1.0"
projects[taxonomy_manager][subdir] = "contrib"
projects[wysiwyg_filter][version] = "1.6-rc2"
projects[wysiwyg_filter][subdir] = "contrib"
projects[backup_migrate][version] = "3.0"
projects[backup_migrate][subdir] = "contrib"
projects[block_class][version] = "1.3"
projects[block_class][subdir] = "contrib"
projects[context][version] = "3.2"
projects[context][subdir] = "contrib"
projects[custom_breadcrumbs][version] = "1.0-alpha1"
projects[custom_breadcrumbs][subdir] = "contrib"
projects[entity][version] = "1.5"
projects[entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-alpha3"
projects[file_entity][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta7"
projects[field_collection][subdir] = "contrib"
projects[flag][version] = "3.5"
projects[flag][subdir] = "contrib"
projects[google_analytics][version] = "2.0"
projects[google_analytics][subdir] = "contrib"
projects[menu_block][version] = "2.4"
projects[menu_block][subdir] = "contrib"
projects[relation][version] = "1.0-rc5"
projects[relation][subdir] = "contrib"
projects[token][version] = "1.5"
projects[token][subdir] = "contrib"
projects[webform][version] = "4.0"
projects[webform][subdir] = "contrib"
projects[nodeformcols][version] = "1.0"
projects[nodeformcols][subdir] = "contrib"
projects[smart_trim][version] = "1.4"
projects[smart_trim][subdir] = "contrib"
projects[xmlsitemap][version] = "2.0"
projects[xmlsitemap][subdir] = "contrib"

; Contrib Dev Versions
; Because Dev Versions can change we want to target the specific commit hash
; that this build works with.
;
; projects[backup_migrate_files][version] = "1.x-dev"
; projects[backup_migrate_files][subdir] = "contrib"
; projects[backup_migrate_files][download][type] = "git"
; projects[backup_migrate_files][download][url] = "http://git.drupal.org/project/backup_migrate_files.git"
; projects[backup_migrate_files][download][revision] = "51562f652b6935ce005dddddd2529b4f7392998e"

projects[context_respect][version] = "1.x-dev"
projects[context_respect][subdir] = "contrib"
projects[context_respect][download][type] = "git"
projects[context_respect][download][url] = "http://git.drupal.org/project/context_respect.git"
projects[context_respect][download][revision] = "834519f6a95a356425aabc4216c08e2688859174"

projects[css_injector][version] = "1.x-dev"
projects[css_injector][subdir] = "contrib"
projects[css_injector][download][type] = "git"
projects[css_injector][download][url] = "http://git.drupal.org/project/css_injector.git"
projects[css_injector][download][revision] = "41bee7e4421ecfc52a6b673eef6fcde875282a2b"

; Contributed themes
; ------------------

projects[cube][version] = "1.4"
projects[rubik][version] = "4.1"
projects[tao][version] = "3.1"
