#!/bin/bash
#Information about where all the resources are and where they should go.

# The theme list
resource_git_themes_file=$SCRIPTPATH"/scripts/includes/resources.themes.git.inc"

# The module list
resource_git_modules_file=$SCRIPTPATH"/scripts/includes/resources.modules.git.inc"
resource_git_modules_core_file=$SCRIPTPATH"/scripts/includes/resources.core.modules.git.inc"
resource_jsa_git_modules_file=$SCRIPTPATH"/scripts/includes/resources.jsa.modules.git.inc"
resource_jsa_contrib_modules_file=$SCRIPTPATH"/scripts/includes/resources.jsa.modules.contrib.inc"

# The contrib list
resource_contrib_modules_file=$SCRIPTPATH"/scripts/includes/resources.modules.contrib.inc"
resource_contrib_modules_core_file=$SCRIPTPATH"/scripts/includes/resources.core.modules.contrib.inc"

# The patch list
resource_patches_contrib_file=$SCRIPTPATH"/scripts/includes/resources.patches.contrib.inc"

# The Libraries List
resources_libraries_git_file=$SCRIPTPATH"/scripts/includes/resources.libraries.git.inc"

#Profiles
resource_git_profiles_file=$SCRIPTPATH"/scripts/includes/resources.profiles.git.inc"
